language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "cookie-rater-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: cookie-rater
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: Hbdh9jpr0pLXt2HQWzSLoB4H12u77KG6SOrAGMh1ogAaxj1P7J5axrAWHyI2e6IzR1IZhroKrQWIZWBlZPM8bBmrd0yaAU25xUgcNooSjhhPIAx4wyxpa8emuCjR7FUmgTxi0jHjkWki/8ze4TqK9jOwgdVyVsj5S+ceeoBcTtc6g2NSKd7Xy6RaPyzZNTBbq2hHxjoMxe9LlHNzXmdwO23BdbfrMqZ01ypY6+pBQPBYvC94a4hLeiYbNPzIcCD/52B/3U0YKASZbawagtMMGQa7+Ul9pIVQbtGGVW5k0zox07UOVJ7uSIztrP9czohMlWQ7bOIxTsPaPY9TFgXIbNuGe61RvOViYIW0qhgKEkZ5nTL+whNeudMGCfhEmwaoK5a/FhX9YzVXBxohJTF/oUxVrk/wlcul1UDXykN0lMBLXD/PeIvIdlppDlT1Vorl957Ei4sphWMo7MNOSJ4p0Xl7hrqzdfRsIUPdf5X2gbxb/CLC4BEkp/WBz46ryhHWxI17CFtEJdaNLNesPAC/UhdCblkS0o0bUWzjPKLTYSPbIIayj3ydJ4ni81sd17tRPzfCHhd/n7R4m4BP2GTUpPB/bSki8G4Cg9fB3KB3zrhsK3ldb61fD0fGgUhv86FSh2c8U4Ve+8SwxFNecVuwUFTesM+w3qC4sXdoZlw7ddI=
